volumes:
  prometheus_data: {}
services:
  sd_bridge:
    image: sedracoin/sedra_bridge:latest
    container_name: sd_bridge
    restart: unless-stopped
    user: "0"
    command:
      - '-log=true'
      - '-stats=false'
      - '-stratum=:5555'
      - '-prom=:2114'
      - '-sedra=host.docker.internal:22110'
    ports:
      - 5555:5555
      - 2114:2114
    extra_hosts:
      - host.docker.internal:host-gateway
  grafana:
    image: grafana/grafana-oss:latest
    container_name: sd_grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ./docker/grafana:/var/lib/grafana
#    env_file:
#      - ./docker/grafana.env
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
  prometheus:
    image: prom/prometheus:latest
    container_name: sd_prom
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./docker/prometheus-internal.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
